lab:
  Mono:
    black:
      max:
      - 89
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 150
      - 106
      min:
      - 0
      - 0
      - 0
    dark_green:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 112
      - 186
      - 165
      min:
      - 85
      - 145
      - 147
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
  Stereo:
    black:
      max:
      - 90
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 255
      - 110
      min:
      - 0
      - 0
      - 0
    dark_green:
      max:
      - 128
      - 127
      - 130
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 104
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 165
      - 104
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 135
      - 129
      - 132
size:
  height:
  - 480
  width:
  - 640
